name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download test-report.json artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report.json
      - name: Create test summary
        run: node ./.dist/test-runner/action-summary.js
