name: 'CI'
on:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4 # checkout the repo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci # install packages
      - run: ./module-week.sh # run tests (configured to use jest-junit reporter)
      - uses: actions/upload-artifact@v4 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: junit.xml
