name: 'CI'
on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci # install packages
      - run: ./test-action.sh # run tests (configured to use jest-junit reporter)
      - name: Adding markdown
        if: success() || failure()
        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY
