name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI'] # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-report
      - name: Display structure of downloaded files
        run: |
          echo $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Create test summary
        run: node ./.dist/test-runner/action-summary.js
